package com.macaw.entity;

// Generated 2012/7/15 ¤U¤È 10:39:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name = "settings", catalog = "macaw")
public class Settings implements java.io.Serializable {

	private SettingsId id;
	private Integer setn1;
	private Integer setn2;
	private String setc1;
	private String setc2;
	private String setc3;

	public Settings() {
	}

	public Settings(SettingsId id) {
		this.id = id;
	}

	public Settings(SettingsId id, Integer setn1, Integer setn2, String setc1,
			String setc2, String setc3) {
		this.id = id;
		this.setn1 = setn1;
		this.setn2 = setn2;
		this.setc1 = setc1;
		this.setc2 = setc2;
		this.setc3 = setc3;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "setkey", column = @Column(name = "SETKEY", nullable = false, length = 10)),
			@AttributeOverride(name = "setdesc", column = @Column(name = "SETDESC", nullable = false, length = 50)),
			@AttributeOverride(name = "setname", column = @Column(name = "SETNAME", nullable = false, length = 30)) })
	public SettingsId getId() {
		return this.id;
	}

	public void setId(SettingsId id) {
		this.id = id;
	}

	@Column(name = "SETN1")
	public Integer getSetn1() {
		return this.setn1;
	}

	public void setSetn1(Integer setn1) {
		this.setn1 = setn1;
	}

	@Column(name = "SETN2")
	public Integer getSetn2() {
		return this.setn2;
	}

	public void setSetn2(Integer setn2) {
		this.setn2 = setn2;
	}

	@Column(name = "SETC1", length = 100)
	public String getSetc1() {
		return this.setc1;
	}

	public void setSetc1(String setc1) {
		this.setc1 = setc1;
	}

	@Column(name = "SETC2", length = 100)
	public String getSetc2() {
		return this.setc2;
	}

	public void setSetc2(String setc2) {
		this.setc2 = setc2;
	}

	@Column(name = "SETC3", length = 100)
	public String getSetc3() {
		return this.setc3;
	}

	public void setSetc3(String setc3) {
		this.setc3 = setc3;
	}

}
