package com.macaw.entity;

// Generated 2012/7/17 ¤U¤È 09:38:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SettingsId generated by hbm2java
 */
@Embeddable
public class SettingsId implements java.io.Serializable {

	private String setkey;
	private String setdesc;
	private String setname;

	public SettingsId() {
	}

	public SettingsId(String setkey, String setdesc, String setname) {
		this.setkey = setkey;
		this.setdesc = setdesc;
		this.setname = setname;
	}

	@Column(name = "setkey", nullable = false, length = 10)
	public String getSetkey() {
		return this.setkey;
	}

	public void setSetkey(String setkey) {
		this.setkey = setkey;
	}

	@Column(name = "setdesc", nullable = false, length = 50)
	public String getSetdesc() {
		return this.setdesc;
	}

	public void setSetdesc(String setdesc) {
		this.setdesc = setdesc;
	}

	@Column(name = "setname", nullable = false, length = 30)
	public String getSetname() {
		return this.setname;
	}

	public void setSetname(String setname) {
		this.setname = setname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SettingsId))
			return false;
		SettingsId castOther = (SettingsId) other;

		return ((this.getSetkey() == castOther.getSetkey()) || (this
				.getSetkey() != null && castOther.getSetkey() != null && this
				.getSetkey().equals(castOther.getSetkey())))
				&& ((this.getSetdesc() == castOther.getSetdesc()) || (this
						.getSetdesc() != null && castOther.getSetdesc() != null && this
						.getSetdesc().equals(castOther.getSetdesc())))
				&& ((this.getSetname() == castOther.getSetname()) || (this
						.getSetname() != null && castOther.getSetname() != null && this
						.getSetname().equals(castOther.getSetname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSetkey() == null ? 0 : this.getSetkey().hashCode());
		result = 37 * result
				+ (getSetdesc() == null ? 0 : this.getSetdesc().hashCode());
		result = 37 * result
				+ (getSetname() == null ? 0 : this.getSetname().hashCode());
		return result;
	}

}
