package com.macaw.entity;

// Generated 2012/7/14 ¤U¤È 07:22:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name = "settings", catalog = "macaw")
public class Settings implements java.io.Serializable {

	private String setkey;
	private String setname;
	private String setdesc;
	private Integer setn1;
	private Integer setn2;
	private String setc1;
	private String setc2;
	private String setc3;

	public Settings() {
	}

	public Settings(String setkey) {
		this.setkey = setkey;
	}

	public Settings(String setkey, String setname, String setdesc,
			Integer setn1, Integer setn2, String setc1, String setc2,
			String setc3) {
		this.setkey = setkey;
		this.setname = setname;
		this.setdesc = setdesc;
		this.setn1 = setn1;
		this.setn2 = setn2;
		this.setc1 = setc1;
		this.setc2 = setc2;
		this.setc3 = setc3;
	}

	@Id
	@Column(name = "SETKEY", unique = true, nullable = false, length = 10)
	public String getSetkey() {
		return this.setkey;
	}

	public void setSetkey(String setkey) {
		this.setkey = setkey;
	}

	@Column(name = "SETNAME", length = 30)
	public String getSetname() {
		return this.setname;
	}

	public void setSetname(String setname) {
		this.setname = setname;
	}

	@Column(name = "SETDESC", length = 50)
	public String getSetdesc() {
		return this.setdesc;
	}

	public void setSetdesc(String setdesc) {
		this.setdesc = setdesc;
	}

	@Column(name = "SETN1")
	public Integer getSetn1() {
		return this.setn1;
	}

	public void setSetn1(Integer setn1) {
		this.setn1 = setn1;
	}

	@Column(name = "SETN2")
	public Integer getSetn2() {
		return this.setn2;
	}

	public void setSetn2(Integer setn2) {
		this.setn2 = setn2;
	}

	@Column(name = "SETC1", length = 100)
	public String getSetc1() {
		return this.setc1;
	}

	public void setSetc1(String setc1) {
		this.setc1 = setc1;
	}

	@Column(name = "SETC2", length = 100)
	public String getSetc2() {
		return this.setc2;
	}

	public void setSetc2(String setc2) {
		this.setc2 = setc2;
	}

	@Column(name = "SETC3", length = 100)
	public String getSetc3() {
		return this.setc3;
	}

	public void setSetc3(String setc3) {
		this.setc3 = setc3;
	}

}
